## W1622 (next-method-called)

### :x: Problematic code:

```python
# to be addded
```

### :heavy_check_mark: Correct code:

```python
# to be added
```

### Rationale:

 *Called a next() method on an object*
  Used when an object's next() method is called (Python 3 uses the next()
  built-in function) This message belongs to the python3 checker.



### Related resources:

- [Testcases](#)
- [Issue Tracker](https://github.com/PyCQA/pylint/issues?q=is%3Aissue+%22next-method-called%22+OR+%22W1622%22)
