## W0150 (lost-exception)

### :x: Problematic code:

```python
# to be addded
```

### :heavy_check_mark: Correct code:

```python
# to be added
```

### Rationale:

 *%s statement in finally block may swallow exception*
  Used when a break or a return statement is found inside the finally clause of
  a try...finally block the exceptions raised in the try clause will be
  silently swallowed instead of being re-raised. This message belongs to the
  basic checker.



### Related resources:

- [Testcases](#)
- [Issue Tracker](https://github.com/PyCQA/pylint/issues?q=is%3Aissue+%22lost-exception%22+OR+%22W0150%22)
